var MSG = {
  joinRoom: 'joinRoom',
  leaveRoom: 'leaveRoom',
  leftRoom: 'leftRoom',
  mediaAllowed: 'mediaAllowed', // 'allowed', 'error', 'initial', 'started'
  browserReqs: 'browserReqs',
  joinError: 'joinError',
  userChanged: 'userChanged',
  userJoined: 'userJoined',
  userLeft: 'userLeft',
  joinedRoom: 'joinedRoom',
  audioSetup: 'setup_audio',
  setSpeakerEnable: 'setSpeakerEnable',
  setSpeakerEnabled: 'setSpeakerEnabled',
  setSpeakerVolume: 'setSpeakerVolume',
  setMicrophoneEnable: 'setMicrophoneEnable',
  setMicrophoneEnabled: 'setMicrophoneEnabled',
  sendChatMessage: 'sendChatMessage',
  receiveChatMessage: 'receiveChatMessage',
  receiveMessage: 'receiveMessage',
  setThisUserName: 'setThisUserName',
  thisUserChanged: 'thisUserChanged',
  setThisUserTalking: 'setThisUserTalking',
  setLockEnable: 'setLockEnable',
  setLockEnabled: 'setLockEnabled',
  startPresentation: 'startPresentation',
  stopPresentation: 'stopPresentation',
  setPresentationPage: 'setPresentationPage',
  setUserViewPresentation: 'setUserViewPresentation',
  setUserHandRaise: 'setUserHandRaise',
  startRecording: 'startRecording',
  stopRecording: 'stopRecording',
  sendFileMessage: 'sendFileMessage',
  receiveFileMessage: 'receiveFileMessage',
  audioMessage: 'audioMessage',
  reconnectError: 'reconnectError',
  userTalking: 'userTalking',
  ping: 'ping',
  pong: 'pong',
  connected: 'connected',
  disconnected: 'disconnected',
  reconnected: 'reconnected',
  kill: 'kill',
  error: 'error',
  metric: 'metric',
  ready: 'ready',
  connectionTimeout: 'connectionTimeout',
  connectionFailure: 'connectionFailure'
};

module.exports = MSG;
